# docker-compose.yml
version: '3'
services:
  dorayaki-prod:
    container_name: dorayaki-prod
    volumes:
      - ../../:/app:z
    build:
        context: ../../
        dockerfile: builds/server-prod/Dockerfile
    env_file: ../../builds/server-prod/.env
    ports:
      - 8080:8080
    networks:
      - dbconnect
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    container_name: mariadb-prod
    build: ../../builds/database-prod
    env_file: ../../builds/database-prod/.env
    ports:
      - 3306:3306
    networks:
      - dbconnect
    restart: unless-stopped
networks:
  dbconnect:
    driver: bridge
