# docker-compose.yml
version: '3'
services:
  dorayaki-dev:
    container_name: dorayaki-dev
    volumes:
      - ../../:/app:z
    build:
        context: ../../
        dockerfile: builds/server/Dockerfile
    env_file: ../../builds/server/.env
    ports:
      - 8080:8080
    networks:
      - dbdorayakiconnect
    depends_on:
      - mariadb-dorayaki
    restart: on-failure
  mariadb-dorayaki:
    container_name: mariadb-dorayaki-dev
    build: ../../builds/database
    env_file: ../../builds/database/.env
    ports:
      - 3308:3306
    networks:
      - dbdorayakiconnect
    restart: on-failure
networks:
  dbdorayakiconnect:
    driver: bridge
